package net.jfabricationgames.gdx.object;

public enum GameObjectType {
	BASIC, //
	DESTROYABLE, //
	INTERACTIVE, //
	LOCKED, // 
	STATE_SWITCH, //
	MULTI_STATE_SWITCH, //
	MOVING, //
	SPAWN_POINT, //
	EVENT_OBJECT, //
	MOVABLE, //
	DRAGGABLE, //
	ANIMATION, //
	PERSISTENT_ANIMATION, //
	CONFIG_OBJECT, //
	FORCE, //
	TRAVERSEABLE, //
	ENEMY_PATH_BLOCKER, //
	ROTATING_PUZZLE, //
	
	// specialized types
	DWARVEN_GUARDIAN_CONSTRUCT_SWITCH, //
	DWARVEN_GUARDIAN_CONSTRUCT_TORCH, //
}
